global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'monitoring-item'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'

    static_configs:
      - targets: ['prometheus:9090', 'node_exporter:9100', 'cadvisor:8080']
        labels:
          service: 'monitor'
