package com.loltmi.riotapi.entity;

import com.fasterxml.jackson.databind.ser.Serializers.Base;
import com.loltmi.riotapi.dto.MatchDto.Info.ParticipantDto.ChallengesDto;
import jakarta.persistence.ConstraintMode;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Entity
@Getter
@AllArgsConstructor
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class MatchExtra extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Integer allInPings;
    private Integer assistMePings;
    private Integer basicPings;
    private Integer commandPings;
    private Integer dangerPings;
    private Integer enemyMissingPings;
    private Integer enemyVisionPings;
    private Integer getBackPings;
    private Integer holdPings;
    private Integer needVisionPings;
    private Integer onMyWayPings;
    private Integer pushPings;
    private Integer visionClearedPings;

    private Integer controlWardsPlaced;

    private Integer visionWardsBoughtInGame;
    private Integer wardsPlaced;

    private Integer firstTurretKilled;
    private Float firstTurretKilledTime;

    private Integer initialCrabCount;

    private Integer summoner1Casts;
    private Integer summoner1Id;
    private Integer summoner2Casts;
    private Integer summoner2Id;

    private Boolean win;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "matches_id", foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT))
    private Matches matches;

    private Integer assists;
    private Integer baronKills;
    private Integer bountyLevel;
    private Integer champExperience;
    private Integer champLevel;
    private Integer championId;
    private String championName;
    private Integer championTransform; // Kayn's transformations(0 - None, 1 - Slayer, 2 - Assassin)
    private Integer consumablesPurchased;
    private Integer baronBuffGoldAdvantageOverThreshold;
    private Float controlWardTimeCoverageInRiverOrEnemyHalf;
    private Integer earliestBaron;
    private Integer earliestDragonTakedown;
    private Integer earliestElderDragon;
    private Integer earlyLaningPhaseGoldExpAdvantage;
    private Integer fasterSupportQuestCompletion;
    private Integer fastestLegendary;
    private Integer hadAfkTeammate;
    private Integer highestChampionDamage;
    private Integer highestCrowdControlScore;
    private Integer highestWardKills;
    private Integer junglerKillsEarlyJungle;
    private Integer killsOnLanersEarlyJungleAsJungler;
    private Integer laningPhaseGoldExpAdvantage;
    private Integer legendaryCount;
    private Float maxCsAdvantageOnLaneOpponent;
    private Integer maxLevelLeadLaneOpponent;
    private Integer mostWardsDestroyedOneSweeper;
    private Integer mythicItemUsed;
    private Integer playedChampSelectPosition;
    private Integer soloTurretsLategame;
    private Integer takedownsFirst25Minutes;
    private Integer teleportTakedowns;
    private Integer thirdInhibitorDestroyedTime;
    private Integer threeWardsOneSweeperCount;
    private Float visionScoreAdvantageLaneOpponent;
    private Integer InfernalScalePickup;
    private Integer fistBumpParticipation;
    private Integer voidMonsterKill;
    private Integer abilityUses;
    private Integer acesBefore15Minutes;
    private Float alliedJungleMonsterKills;
    private Integer baronTakedowns;
    private Integer blastConeOppositeOpponentCount;
    private Integer bountyGold;
    private Integer buffsStolen;
    private Integer completeSupportQuestInTime;
    private Float damagePerMinute;
    private Float damageTakenOnTeamPercentage;
    private Integer dancedWithRiftHerald;
    private Integer deathsByEnemyChamps;
    private Integer dodgeSkillShotsSmallWindow;
    private Integer doubleAces;
    private Integer dragonTakedowns;
    private Float effectiveHealAndShielding;
    private Integer elderDragonKillsWithOpposingSoul;
    private Integer elderDragonMultikills;
    private Integer enemyChampionImmobilizations;
    private Float enemyJungleMonsterKills;
    private Integer epicMonsterKillsNearEnemyJungler;
    private Integer epicMonsterKillsWithin30SecondsOfSpawn;
    private Integer epicMonsterSteals;
    private Integer epicMonsterStolenWithoutSmite;
    private Integer flawlessAces;
    private Integer fullTeamTakedown;
    private Float gameLength;
    private Integer getTakedownsInAllLanesEarlyJungleAsLaner;
    private Float goldPerMinute;
    private Integer hadOpenNexus;
    private Integer immobilizeAndKillWithAlly;
    private Integer initialBuffCount;
    private Float jungleCsBefore10Minutes;
    private Integer junglerTakedownsNearDamagedEpicMonster;
    private Float kda;
    private Integer killAfterHiddenWithAlly;
    private Integer killedChampTookFullTeamDamageSurvived;
    private Integer killingSprees;
    private Float killParticipation;
    private Integer killsNearEnemyTurret;
    private Integer killsOnOtherLanesEarlyJungleAsLaner;
    private Integer killsOnRecentlyHealedByAramPack;
    private Integer killsUnderOwnTurret;
    private Integer killsWithHelpFromEpicMonster;
    private Integer knockEnemyIntoTeamAndKill;
    private Integer kTurretsDestroyedBeforePlatesFall;
    private Integer landSkillShotsEarlyGame;
    private Integer laneMinionsFirst10Minutes;
    private Integer lostAnInhibitor;
    private Integer maxKillDeficit;
    private Integer mejaisFullStackInTime;
    private Float moreEnemyJungleThanOpponent;
    private Integer multiKillOneSpell;
    private Integer multikills;
    private Integer multikillsAfterAggressiveFlash;
    private Integer multiTurretRiftHeraldCount;
    private Integer outerTurretExecutesBefore10Minutes;
    private Integer outnumberedKills;
    private Integer outnumberedNexusKill;
    private Integer perfectDragonSoulsTaken;
    private Integer perfectGame;
    private Integer pickKillWithAlly;
    private Integer poroExplosions;
    private Integer quickCleanse;
    private Integer quickFirstTurret;
    private Integer quickSoloKills;
    private Integer riftHeraldTakedowns;
    private Integer saveAllyFromDeath;
    private Integer scuttleCrabKills;
    private Float shortestTimeToAceFromFirstTakedown;
    private Integer skillshotsDodged;
    private Integer skillshotsHit;
    private Integer snowballsHit;
    private Integer soloBaronKills;
    private Integer soloKills;
    private Integer stealthWardsPlaced;
    private Integer survivedSingleDigitHpCount;
    private Integer survivedThreeImmobilizesInFight;
    private Integer takedownOnFirstTurret;
    private Integer takedowns;
    private Integer takedownsAfterGainingLevelAdvantage;
    private Integer takedownsBeforeJungleMinionSpawn;
    private Integer takedownsFirstXMinutes;
    private Integer takedownsInAlcove;
    private Integer takedownsInEnemyFountain;
    private Integer teamBaronKills;
    private Float teamDamagePercentage;
    private Integer teamElderDragonKills;
    private Integer teamRiftHeraldKills;
    private Integer tookLargeDamageSurvived;
    private Integer turretPlatesTaken;
    private Integer turretsTakenWithRiftHerald;
    private Integer turretTakedowns;
    private Integer twentyMinionsIn3SecondsCount;
    private Integer twoWardsOneSweeperCount;
    private Integer unseenRecalls;
    private Float visionScorePerMinute;
    private Integer wardsGuarded;
    private Integer wardTakedowns;
    private Integer wardTakedownsBefore20M;

    //     end ChallengesDto
    private Integer damageDealtToBuildings;
    private Integer damageDealtToObjectives;
    private Integer damageDealtToTurrets;
    private Integer damageSelfMitigated;
    private Integer deaths;
    private Integer detectorWardsPlaced;
    private Integer doubleKills;
    private Integer dragonKills;
    private Boolean eligibleForProgression;
    private Boolean firstBloodAssist;
    private Boolean firstBloodKill;
    private Boolean firstTowerAssist;
    private Boolean firstTowerKill;
    private Boolean gameEndedInEarlySurrender;
    private Boolean gameEndedInSurrender;
    private Integer goldEarned;
    private Integer goldSpent;
    private String individualPosition;
    private Integer inhibitorKills;
    private Integer inhibitorTakedowns;
    private Integer inhibitorsLost;
    private Integer item0;
    private Integer item1;
    private Integer item2;
    private Integer item3;
    private Integer item4;
    private Integer item5;
    private Integer item6;
    private Integer itemsPurchased;
//    private Integer killingSprees;
    private Integer kills;
    private String lane;
    private Integer largestCriticalStrike;
    private Integer largestKillingSpree;
    private Integer largestMultiKill;
    private Integer longestTimeSpentLiving;
    private Integer magicDamageDealt;
    private Integer magicDamageDealtToChampions;
    private Integer magicDamageTaken;
    private Integer neutralMinionsKilled;
    private Integer nexusKills;
    private Integer nexusTakedowns;
    private Integer nexusLost;
    private Integer objectivesStolen;
    private Integer objectivesStolenAssists;
    private Integer pentaKills;
    private Integer physicalDamageDealt;
    private Integer physicalDamageDealtToChampions;
    private Integer physicalDamageTaken;
    private Integer placement;
    private Integer profileIcon;
    private String puuid;
    private Integer quadraKills;
    private String riotIdGameName;
    private String riotIdName;
    private String riotIdTagline;
    private String role;
    private Integer sightWardsBoughtInGame;
    private Integer spell1Casts;
    private Integer spell2Casts;
    private Integer spell3Casts;
    private Integer spell4Casts;
    private String summonerId;
    private Integer summonerLevel;
    private String summonerName;
    private Boolean teamEarlySurrendered;
    private Integer teamId;
    private String teamPosition;
    private Integer timeCCingOthers;
    private Integer timePlayed;
    private Integer totalAllyJungleMinionsKilled;
    private Integer totalDamageDealt;
    private Integer totalDamageDealtToChampions;
    private Integer totalDamageShieldedOnTeammates;
    private Integer totalDamageTaken;
    private Integer totalEnemyJungleMinionsKilled;
    private Integer totalHealsOnTeammates;
    private Integer totalMinionsKilled;
    private Integer totalTimeCCDealt;
    private Integer totalTimeSpentDead;
    private Integer totalUnitsHealed;
    private Integer tripleKills;
    private Integer trueDamageDealt;
    private Integer trueDamageDealtToChampions;
    private Integer trueDamageTaken;
    private Integer turretKills;
//    private Integer turretTakedowns;
    private Integer turretsLost;
    private Integer unrealKills;
    private Integer visionScore;
    private Integer wardsKilled;

}