# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
##
name: Auto deploy to NCP

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # JDK 21 설치
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

      # SECRET_YML 파일 생성
    - name: Make application-secret.yml
      run: |
        cd ./common/src/main/resources # resources 폴더로 이동
        touch ./application-secret.yml # application.yml 생성
        echo "${{ secrets.SECRET_YML }}" > ./application-secret.yml # github actions에서 설정한 값을 application.yml 파일에 쓰기
        cd /home/runner/work/LOLTMI/LOLTMI
        cd ./batch/src/main/resources
        touch ./application-secret.yml # application.yml 생성
        echo "${{ secrets.SECRET_YML }}" > ./application-secret.yml
        
    # Gradle Build를 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Gradle Build (test 제외)
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # DockerHub 로그인
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker 이미지 빌드
    - name: Docker Image Build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} .

    # DockerHub Push
    - name: DockerHub Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

  deploy:
    # needs를 통해 build job이 수행 성공시에 작업되도록 설정
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          script: ls batch
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          source: "batch/build/libs/batch-0.0.1-SNAPSHOT.jar"
          target: "/root/jenkins/workspace/spring-batch"
          
    # # NCP 로그인 / docker image pull & run
    # - name: NCP login and docker image pull and run
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.NCP_HOST }}
    #     username: ${{ secrets.NCP_USERNAME }}
    #     password: ${{ secrets.NCP_PASSWORD }}
    #     port: ${{ secrets.NCP_PORT }}
    #     script: |
    #       sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #       sudo docker stop $(sudo docker ps -a -q)
    #       sudo docker rm -f $(sudo docker ps -a -q)
    #       sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
    #       sudo docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
    #       sudo docker image prune -f
          
    # - name: Batch Jar file SCP send
    #   run: |
    #     ls
    #     touch ./key.pem
    #     echo "${{ secrets.NCP_KEY }}" > ./key.pem
    #     chmod 400 ./key.pem
    #     scp -o StrictHostKeyChecking=no -i ./key.pem batch/build/libs/batch-0.0.1-SNAPSHOT.jar root@211.188.48.13:/root/jenkins/workspace/spring-batch

